Title with background image
alkemyTech/OT91-server pull request #1
Opened 2021-10-27 16:15 UTC by andrespereyra-it

**Summary**
Title view. Can receive a text and a background image.

**Evidence**
![default](https://user-images.githubusercontent.com/73605405/139104214-c23b869e-2f43-4f66-9397-4e4340d58105.png)

2021-10-27 22:46 UTC, saralavanchy requested changes
Please review the comments

2021-10-27 22:46 UTC, saralavanchy commented on src/Components/Title/Title.js
> +import DefaultImage from "../../assets/default.jpg";
The name of the image is too generic and the container folder do not give too muc information of it. If we go to assets folder we can make the question "What this image is for? Is default image of what?", you can create a folder inside assets called title and put the image on it or change the name to defaultTitle or something more clear.

2021-10-27 22:46 UTC, saralavanchy commented on src/Components/Title/Title.js
> +import DefaultImage from "../../assets/default.jpg";
Also following the convention of the others folders name the folder name should be Assets and not assets

2021-10-27 22:46 UTC, saralavanchy commented on src/Components/Title/Title.js
> +  const titleMock = "Title";
following the user story requirements this image and title should come from the props. Remember that this is a generic component.
note: I prefer to receive an object like {title, image} instead of props because its easier to see the contract of the function.

2021-10-27 22:46 UTC, saralavanchy commented on src/Components/Title/Title.js
> +export default function Title(props) {
following the rest of the code convention this should be a const and not a function.
```
const Title= () => {
    code here ...
};
export default Title;
```

2021-10-27 22:46 UTC, saralavanchy commented on src/Components/Title/Title.js
> +        }}
If you want to create a styled component please create a styles folder and on it add a BoxStyle object. Then here replace all this styles with the BoxStyle object.
By this way if then we need to create another box we are sure that if we need to modify the style both boxes will have the same style.
Other option is to create a CustomBox component and then use it here instead of material-ui box.

2021-10-27 22:46 UTC, saralavanchy commented on src/Components/Title/Title.js
> +        }}
Also, this should have an id. Because its a generic component you can add the id to the components props.

2021-10-27 22:46 UTC, saralavanchy commented on src/Components/Title/Title.js
> +  }, []);
you should add imageMock on [] so it will be refresed only if imageMock change.

2021-10-27 22:46 UTC, saralavanchy commented on src/Components/Title/Title.js
> +  }, []);
also instead of two setTitleImage you can have a const to save the title image and then set it on the titleImage:
```
const image= imageMock ? imageMock : DefaultImage;
setTitleImage(image);
```

2021-10-28 21:44 UTC, andrespereyra-it commented on src/Components/Title/Title.js
> +import DefaultImage from "../../assets/default.jpg";
Once the changes are commited, besides renaming `assets` folder for `Assets`, I'll need to add the folder `Title` inside the `Assets` folder and move the `default.jpg` file there.

2021-10-28 21:44 UTC, andrespereyra-it commented on src/Components/Title/Title.js
> +        }}
Once the changes are commited, I'll need to add the folder `Style` in `src` with a `BoxStyle.css` file.

2021-10-31 22:35 UTC, saralavanchy approved these changes

2021-10-31 23:04 UTC, merged