Feat/Actividades/Mostrar errores cuando las peticiones no se realicen correctamente
alkemyTech/OT91-server pull request #108
Opened 2021-11-16 15:23 UTC by TelmaKn

##SUMMARY
Using the reusable alert components, this component displays an error to the user when requests made from the activity service have an error

##CHANGES ADDED
-Add the reusable component errorCrudMessage to handle the errors in the crud methods passing only the end of the error message depending on the component that is executing it.
-Logic to handle errors in raw service methods
-Fixes in environment variables because some paths were not working
-Fix in createOrUpdate function because it didn't work correctly
-Customization of the service component for a more unified and clean code.
-Change of routes in activity files due to export mode change in activity service 

##TEST
Screenshot tests contain a successful call (which can be viewed in the network history) and a last rejected call
![GetById](https://user-images.githubusercontent.com/83502436/142013684-b8dfe3b6-5332-43dd-8bbe-11b6fba969a3.jpg)
![Create](https://user-images.githubusercontent.com/83502436/142013692-0d09a66c-1df6-4bc9-9c76-09d8b293cde5.png)
![Delete (2)](https://user-images.githubusercontent.com/83502436/142013700-1cce49f9-7693-4f3b-a173-ea44106d90b2.png)
![Modify](https://user-images.githubusercontent.com/83502436/142013705-3025cdb9-9721-4af7-9b02-922d2f817f2d.png)
.

##USERSTORY
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT91/boards/145?modal=detail&selectedIssue=OT91-104&assignee=70121%3Aad4a2c05-0941-42e8-af44-540b8eff3169
The tests have been recorded passing the data to the components through the getNews function and simulating slow internet to be able to see the loading component well.
New Detail Component:

2021-11-18 17:40 UTC, saralavanchy requested changes

2021-11-18 17:40 UTC, saralavanchy commented on src/Components/Activities/ActivitiesCards/ActivitiesCards.js
> +import activityService from '../../../Services/activityService';
I think that this should be
```
 import * as activityService from '../../../Services/activityService';
```

2021-11-18 21:47 UTC, TelmaKn commented on src/Components/Activities/ActivitiesCards/ActivitiesCards.js
> +import activityService from '../../../Services/activityService';
ieii!! I like that way much more. I thought we had to do it this other way. There I changed it and fixed the method names. :)

2021-11-19 18:21 UTC, saralavanchy approved these changes

2021-11-19 18:21 UTC, merged