Formulario Login
alkemyTech/OT91-server pull request #2
Opened 2021-10-27 17:43 UTC by ArielSurco

**##SUMMARY**
Email and password fields validation with Formik.

**##CHANGES ADDED**
- Text fields changed to email and password fields
- validateLogin function: It validates that email and password fields are not empty and comply with their corresponding pattern (Using regular expressions).
- Form handling with Formik library
- Corrections made by eslint

**##CORRECTIONS ADDED**
- Rename hasValue to notHasValue
- Add hasRequiredError: Check that the field is not empty and set error: "Dato obligatorio"
- Move functions to src/Utils/validation
- Use object to get regular expressions, to validate form fields
- Refactor validateLogin

2021-10-27 22:23 UTC, saralavanchy requested changes
Great Job! please read the comments and apply feedback.

2021-10-27 22:23 UTC, saralavanchy commented on src/Services/publicApiService.js
> +        Group: 1                //Aqui va el ID del equipo!!
Group 91

2021-10-27 22:23 UTC, saralavanchy commented on src/Services/privateApiService.js
> +        Group: 1                //Aqui va el ID del equipo!!
Group 91

2021-10-27 22:23 UTC, saralavanchy commented on src/Components/Auth/LoginForm.js
> +const hasValue = (data, value) => data[value] && data[value].length > 0
I like this function! maybe we can move it to a utils file so we can reuse it on other parts of the code.

2021-10-27 22:23 UTC, saralavanchy commented on src/Components/Auth/LoginForm.js
> +const isValidValue = (regExp, value) => regExp.test(value)
same comment of hasValue function

2021-10-27 22:23 UTC, saralavanchy commented on src/Components/Auth/LoginForm.js
> +    return errors;
@MartinCaparros has a similar functionallity to validate email and password, because this piece of code is pretty similar of his code maybe you can talk and create a code on a validation file that can be reused on both user stories.

2021-10-27 22:23 UTC, saralavanchy commented on src/Components/Auth/LoginForm.js
> +    if(!hasValue(formData, 'password'))
instead of using !function maybe you can change the function to be notHasValue(). Sometimes, for some programmers, is difficult to read negated functions. Something like `if(notHasValue(formData, 'email'))` is faster to read.

2021-10-27 22:23 UTC, saralavanchy commented on src/Components/Auth/LoginForm.js
> +        errors.email = 'Invalid email';
Im not sure if this if else if is really necessary, maybe its better to have all the validation on only on if and merge the messages:
```
const notValidEmail = notHasValue(formData, 'email') || notValidValue(emailRegExp, formData.email);
if(notValidEmail) errors.email = 'Email is required and should be a valid email';
```

2021-10-27 22:23 UTC, saralavanchy commented on src/Components/Auth/LoginForm.js
> +    else if(!isValidValue(passwordRegExp, formData.password))
same of email if/else

2021-10-27 22:23 UTC, saralavanchy commented on src/Components/Auth/LoginForm.js
> +            const tempObj = formData;
What this temporal object is for? maybe the name is too generic, maybe something more expecific like temporalFormData. Im not sure if that is what you are trying to store.

2021-10-28 14:39 UTC, ArielSurco commented on src/Components/Auth/LoginForm.js
> +            const tempObj = formData;
In the validation section of the ticket it says: "Al no disponer aún del servicio de solicitudes HTTP, solo almacenar los campos completos en un objeto (para luego enviarlo)", that's why I created that object. I should change the onSubmit for `onSubmit: formData => {  }`?

2021-10-31 22:38 UTC, saralavanchy approved these changes, later dismissed

2021-10-31 22:40 UTC, saralavanchy commented on src/Components/Auth/LoginForm.js
> +            const tempObj = formData;
the main point of the comment is that formData is a generic name, and do not say anything about its content. The name should explain to the rewiever whats its being done with the object.

2021-10-31 22:42 UTC, saralavanchy commented on src/Components/Auth/LoginForm.js
> +            const tempObj = formData;
maybe instead of 'formData' a name like 'credentials' is more representative of the object's content

2021-10-31 23:04 UTC, ArielSurco commented on src/Components/Auth/LoginForm.js
> +            const tempObj = formData;
I understand, change applied

2021-10-31 23:08 UTC, saralavanchy approved these changes

2021-10-31 23:09 UTC, merged