Feat/actividades/crear componente conectenido de actividad
alkemyTech/OT91-server pull request #23
Opened 2021-11-02 14:22 UTC by julian624

![image](https://user-images.githubusercontent.com/87099497/139864494-27a05e0d-8d7f-46d5-bc53-71bb5feca909.png)

This is just a little component of activities content, they recibe a description in the props ( because in the ong api, description  is the closest thing to content) and renderize html code with ReactHtmlParser

i dont know if i need to recibe a new "content" from activities, but i can change it if you need

2021-11-03 00:15 UTC, saralavanchy requested changes

2021-11-03 00:15 UTC, saralavanchy commented on src/Components/Activities/ActivitiesContent.js
> +function ActivitiesContent(description) {
seguir la misma logica del resto del proyecto y utilizar 
```
const ActivitiesContent =({description}) => {
   code
}
export default ActivitiesContent;
```

2021-11-03 01:03 UTC, julian624 commented on src/Components/Activities/ActivitiesContent.js
> +function ActivitiesContent(description) {
ok teacher sorry!!! already changed

2021-11-04 00:39 UTC, saralavanchy requested changes
Please do not remove any library, only add the new library that you are using

2021-11-04 01:20 UTC, closed without merging