Home layout created.
alkemyTech/OT91-server pull request #24
Opened 2021-11-02 14:57 UTC by MartinCaparros

Home folder, index.js, route created, all placeholders created with demo strings, also i fixed some spacing issues on several files and fix some routes also.

Ticket: https://alkemy-labs.atlassian.net/browse/OT91-52

Evidence: 

![Captura de pantalla 2021-11-02 115502](https://user-images.githubusercontent.com/79990559/139872078-b21282f7-65d6-4795-b09e-d57ae812701d.png)

2021-11-03 00:21 UTC, saralavanchy requested changes

2021-11-03 00:21 UTC, saralavanchy commented on src/Components/Activities/ActivitiesForm.js
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Components/Home/index.js
> +
este espacio en blanco no es necesario

2021-11-03 00:21 UTC, saralavanchy commented on src/Components/News/Detail/NewsDetailLayout.js
>          const {data} = await getNewById()
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Components/News/Detail/NewsTittle.js
>  import React from 'react';
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Components/Newsletter/NewsletterForm.js
>      localStorage.setItem("tokenNL","settokenNL")
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Components/Organization/OrganizationData.js
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Components/Title/Title.js
>  import { useState, useEffect } from "react";
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Components/Users/UserModifierForm.js
>              return true;
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Components/utilsData/roleList.js
> -export const rolesList = [{roleId:'Administrador'},{roleId:'Regular'}]
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Services/NewServices/getNewById.js
>  export const getNewById = async (id) => {
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Services/OrganizationInformation.js
>  export const getOrganizationInformation = async () => {
este archivo no es scope de la user story

2021-11-03 00:21 UTC, saralavanchy commented on src/Services/userServices.js
>  export const updateUser = async (id,user) => {
este archivo no es scope de la user story

2021-11-03 13:04 UTC, MartinCaparros commented on src/Components/Home/index.js
> +
Solved!

2021-11-04 00:40 UTC, saralavanchy requested changes
Review the files that are not scope of this PR because you are deleting them.

2021-11-04 23:59 UTC, saralavanchy approved these changes

2021-11-05 12:25 UTC, saralavanchy approved these changes

2021-11-05 12:26 UTC, merged