Parcial register form
alkemyTech/OT91-server pull request #3
Opened 2021-10-27 17:47 UTC by MartinCaparros

Parcial register form created, all fields are validated. The button onClick creates a new object on component's state with the inputs data, also onSubmitting saves the user token.

Link to ticket related: https://alkemy-labs.atlassian.net/browse/OT91-25

![Parcial Register form](https://user-images.githubusercontent.com/79990559/139117469-4cc267d1-9ad6-413d-adc6-768d203237c1.png)

2021-10-27 21:40 UTC, saralavanchy commented on reports/eslint
> +[{"filePath":"C:\\Users\\MD35410931\\Proyectos\\OT91-server\\src\\App.js","messages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecat
We should add this file to .gitignore

2021-10-27 21:56 UTC, MartinCaparros commented on reports/eslint
> +[{"filePath":"C:\\Users\\MD35410931\\Proyectos\\OT91-server\\src\\App.js","messages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecat
Added to .gitignore and removed from the commit

2021-10-27 22:03 UTC, saralavanchy requested changes
Please review all the comments. Good Job!

2021-10-27 22:03 UTC, saralavanchy commented on src/Components/Auth/RegisterForm.js
> -            <input className="input-field" type="text" name="lastName" value={initialValues.lastName} onChange={handleChange} placeholder="Enter last name"></input>
The acceptance criteria says: "En base al formulario entregado como base, debe **agregar** los campos Email, Contraseña y Confirmar contraseña (todos obligatorios)."
Because is add and not replace, we should not delete the existing fields.

2021-10-27 22:03 UTC, saralavanchy commented on src/Components/Auth/RegisterForm.js
> +                placeholder="Reingrese la contraseña"
maybe"Confirmar contraseña" is more user friendly than "Reingrese la contraseña"

2021-10-27 22:03 UTC, saralavanchy commented on src/Components/Auth/RegisterForm.js
> +            console.log(initialValues)
this console.log is necessary? remember to avoid the use of console.log except its absolutely necessary

2021-10-27 22:03 UTC, saralavanchy commented on src/Components/Auth/RegisterForm.js
> +        }
this three parts of code can be resumed on:
```
if (!values[key]) {
    errors[key] = 'Dato Obligatorio';
} else if (validation(values[key])) {
    errors[key] = errorMessage;
}
``` 
so, maybe, we can create a generic method to validate that we can reuse.
If we do not create a method to reuse almost we should save 'Dato Obligatorio' on a const that we can reuse.

2021-10-27 22:03 UTC, saralavanchy commented on src/Components/Auth/RegisterForm.js
> +        } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.email)) {
This else if is not clear to read, maybe we can extract this code in a function to validate emails

2021-10-27 22:03 UTC, saralavanchy commented on src/Components/Auth/RegisterForm.js
> +        } else if (values.password.length < 6 || !includesLetter(values.password) || !includesSymbols(values.password) || !includesNumbers(values.password)) {
maybe we can extract this large validation on a const or a function that lets us know only with read it what is being done here. Something like:
```
const notValidPassword = (password) => validation here
```
then we only call that like this:
```
if (!values.password) {
    errors.password = 'Dato Obligatorio';
} else if (notValidPassword(values.password)) {
    rest of the code here...
}
```

2021-10-27 22:03 UTC, saralavanchy commented on src/Components/Auth/RegisterForm.js
> +            <button className="submit-btn" type="submit">Registrarse</button>
this button do not have an id

2021-10-28 15:13 UTC, MartinCaparros commented
All changes done.

2021-10-31 22:54 UTC, saralavanchy approved these changes

2021-10-31 22:54 UTC, saralavanchy commented on src/Components/Auth/CustomRegisterForm.js
> +
this empty space its not necessary

2021-10-31 22:54 UTC, saralavanchy commented on src/Components/Auth/CustomRegisterForm.js
> +    const validate = values => {
this function should go on the validations file in the Utils folder. But it's not blocking for this first PR

2021-10-31 22:54 UTC, saralavanchy commented on src/Components/Auth/CustomRegisterForm.js
> +    const [initialValues, setInitialValues] = useState({
initial values is a generic name maybe credentials is a more readable name for this view.

2021-10-31 23:13 UTC, merged