Feat/project form/create and edit form projects
alkemyTech/OT91-server pull request #4
Opened 2021-10-28 04:19 UTC by andreajhl

-Add get, post and put functions in projectServer.
-Add project creation and editing form, made with formik and ckeditor.
-add modularized function for rendering formik formulary errors
-add modularized function to obtain the url of the file type inputs
-You don't have styles yet because you have to decide it as a group.

Form:

-title: validation => long (minimum 4 letters)
-image: validation => must exist, and accept jpg or png, render the image above the input when loading it, as expected
-description: validation => must exist
-date: condition => does not allow dates less than the current day

![project](https://user-images.githubusercontent.com/75461111/139186248-8ce4760c-c68c-408f-9363-a86d0c9ff47a.png)

2021-10-28 21:21 UTC, saralavanchy requested changes
I left some comments but the code was a little bit difficult to follow, so, after this changes I will maybe give a better feedback. Thanks!

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +  date=date.toISOString().split('T')[0];
Im not sure what you are trying to do here but it looks like a good candidate for a functions on a date utils file

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +  var date = new Date();
for what is this date? The name is too generic

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +export default function ProjectsForm({idProyect}){
please, follow the convention of the proyect and use ```const ProjectsForn = ({projectId}) => {}```
Also its more redeable projectId than idProyect. In addition, in english is Project and not proyect

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +  const [state, setstate] = useState('');
please use setState instead of setstate, and also, what this state is for, what do it represent? the name is too generic

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +              initialValues={state? {
this validation is too log to be done here, please create a function that get the initial values. Something like 
```
const getInitialValue= () => logic here 
```

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +              validate={(valores)=>{
Please create a validation function for this.

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +              validate={(valores)=>{
Also, if you are writting the code in english it should be values instead of valores

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +                const stringreplace =/'<p>'|['</p>']/gi;
please create an onSubmit function to do this or a function whith a name that explains what is being done here.

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +                idProyect ?  putDataForm( idProyect, values ) :postDataForm(values)
please follow a linament of spaces if you use space before and after ?, use space before and after :

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +                            onChange={( event, editor )=> {
create a function to do this

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +                          <ErrorMessage name='title' component={()=><p className='form_div_error'>{errors.title}</p>}/>
this code is being repeted, please create a function to show it, something like this  (this code is only ilustrative of the suggested change):
```
const showErrorMessage = (name, message) =>  (<ErrorMessage name={name} component={()=><p className='form_div_error'>{message}</p>}/>)
```

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +                                value={undefined}
Please, never use undefined as a value.

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +                                  setFieldValue("image",e)
please, move this code to a function

2021-10-28 21:21 UTC, saralavanchy commented on src/Components/Projects/function/index.js
> +import axios from "axios";
this look to be a service, so it should be on the services folder on a file with the service name that you are creating. I think, (for the name of the folder and the endpoints) that its the projects service, so, create a ProjectsService with a getProject,  createProject and modifyProject functionallities

2021-10-28 21:26 UTC, saralavanchy commented
Please write a more descriptive title of what is being done in this PR. Also in the description maybe some title like
##Summary
##Screenshots
can help to understand the description.
Finally, if you can, please add a link to the user story.

2021-10-28 22:41 UTC, andreajhl commented on src/Components/Projects/ProjectsForm.js
> +  var date = new Date();
The data is so that the creation of the project has as a minimum date the current day

2021-10-29 10:19 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +  var date = new Date();
if its a minimumDate so it should be the name, if its the currentDate its should be the name, if its the projectDate it should be the name.

2021-11-01 01:09 UTC, saralavanchy requested changes

2021-11-01 01:09 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +          onSubmit={async (values)=>{
en el return no debe haber functions, todo lo que sea codigo como por ejemplo esta functionallity onSubmit tiene que ir en una function que luego se llama aca, como hiciste con validateForm

2021-11-01 01:09 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +            projectId ?  modifiedProject( projectId, dataForm ) : createProject(dataForm);
modificar o crear proyecto es logica de negocios y debe estar en el service

2021-11-01 01:09 UTC, saralavanchy commented on src/Components/common/validateForm.js
> +export const validateForm = (values) => {
si en el #13 creaste una carpeta para validations en common, aca este archivo deberia estar en esa carpeta tambien, siempre hay que intentar seguir una misma logica en todo el proyecto para tener el codigo de manera ordenada

2021-11-01 01:09 UTC, saralavanchy commented on src/Components/common/messagesForm.js
> +
el nombre del file deberia ser ErrorsForm ya que lo que contiene es un ErrorsForm.

2021-11-01 01:09 UTC, saralavanchy commented on src/Components/common/getUrlInputFile.js
> +
mismo feedback #13

2021-11-01 01:09 UTC, saralavanchy commented on src/Components/Projects/ProjectsForm.js
> +  const [dataForm, setDataForm] = useState({
siempre es importante cuanto mayor claridad podamos dejar en el codigo mejor. si esta constante es llamada project es mas descriptiva de su contenido que dataForm. dataForm es muy generica y puede ser cualquier cosa que sea data de un form.

2021-11-02 21:21 UTC, saralavanchy approved these changes

2021-11-02 21:45 UTC, merged