Activity Detail Component with Styles in new Style folder. Add routin…
alkemyTech/OT91-server pull request #6
Opened 2021-10-28 05:24 UTC by andrespereyra-it

### Summary

Activity detail view made with Card component from Material-ui.
File with styles for the Card.
Routing added in App.js file.

**Link to ticket related**: https://alkemy-labs.atlassian.net/browse/OT91-50

### Evidence
![Activity Detail](https://user-images.githubusercontent.com/73605405/139626657-005f17f8-b9c2-45cb-9c21-715e339c76aa.png)

2021-10-28 20:28 UTC, saralavanchy requested changes

2021-10-28 20:28 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +import Title from "../../Title/Title";
Take care because this component do not exists on Dev yet. It will exists after the PR is merged

2021-10-28 20:28 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +
this space is unnecessary

2021-10-28 20:28 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +
this space is unnecessary

2021-10-28 20:28 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +
this space is not necessary

2021-10-28 20:28 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +
this space is unnecessary

2021-10-28 20:28 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +    typeof activity.description !== "undefined" &&
why are you testing typeof undefined and not use directly something like ``` activity.description && setActivityDesc(...) ``` ?

2021-10-28 20:28 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +  const [activityDesc, setActivityDesc] = useState("");
is this a list of activities in desc order? is this a description? The name is not clear enought, maybe something like activityDescription (if that is what it is) its a better name.

2021-10-28 20:28 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +        const response = await axios.get(
the calls to the backend on the services. Please move this to the activity service.

2021-10-28 20:29 UTC, saralavanchy commented
this user story depends on #1

2021-10-28 22:24 UTC, andrespereyra-it commented on src/Components/Activities/Detail/Detail.js
> +import Title from "../../Title/Title";
But It is a requirement to use the Title component. Should I wait until you merged the Title PR before send this Component to merge?

2021-10-28 23:46 UTC, andrespereyra-it commented on src/Components/Activities/Detail/Detail.js
> +        const response = await axios.get(
What activity service? Sorry if I overextend but I'm not sure what you mean.
I left it this way because like the api service is not ready, I don't know how the files are going to be called. So I wrote something temporal which works. 
Accordingly to what we discuss in the #libraries discord channel, we were going to use an axios instance. I imagine something similar to this:

**Axios Instance Service file:**
```
export default axios.create({
  baseURL: "http://ongapi.alkemy.org/api/",
  headers: {
    "Content-type": "application/json",
  },
});
```

**HTTP Actions Service file:**
```
const get = (id) => {
  return axiosInstance.get(`/activities/${id}`);
};
```

So, you mean I should replace the axios call in Details.js for something like this?

`import getActivity from "../../../Services/publicApiService"`

`const res = await getActivity.get(id);`

2021-10-31 23:29 UTC, saralavanchy requested changes

2021-10-31 23:29 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +        const response = await axios.get(
lo escribo en españal, siempre que uses business logic tiene que ir en un archivo service. Si el archivo no existe entonces tenes que crearlo, en este caso en services tenes que crear un archivo userService donde se maneje toda la business logic de los users, como get con axios, etc.

2021-10-31 23:29 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +        const response = await axios.get(
o en un activity service depende que grupo de endpoits estas llamando. En este caso la function se llama getUsers pero estas llamando http://ongapi.alkemy.org/api/activities/${id} por lo que el codigo no es claro

2021-10-31 23:29 UTC, saralavanchy commented on src/Components/Activities/Detail/Detail.js
> +        const response = await axios.get(
ademas, la function esta dentro del useEffect, en el useEffect solo se deberian llamar functions

2021-11-01 19:17 UTC, andrespereyra-it commented on src/Components/Activities/Detail/Detail.js
> +        const response = await axios.get(
Done

2021-11-01 22:31 UTC, saralavanchy approved these changes

2021-11-01 22:31 UTC, merged