Feat/Categorías/ Formulario de Creación de Categorías
alkemyTech/OT91-server pull request #8
Opened 2021-10-28 15:33 UTC by TelmaKn

I implemented Formik library for data validations and cleaner code.
I implemented CkEditor library to handle the description input.
I implemented Material Ui for a temporary style until one is agreed with the team.
Add a services file for http
Add a file for raw functions
Add temporary form creation and editing files to handle a boolean that allows rendering of one or the other

![ticket1](https://user-images.githubusercontent.com/83502436/139288441-e5102c1b-efd7-420f-9a22-5044f3209677.png)

2021-10-28 22:31 UTC, saralavanchy requested changes
Category is the singular of Categories, please review all the categorie that you have in the code and make this change. 
Some changes required but in general looks really good the PR

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesFunctions.js
> +export const getCategorie = (id) => async () => {
Category is the singular of categories

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +      const categorieData = functions.getCategorie(id)
use the service directly insted of create functions file, that is the responsabiliy of the service

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +  const [values, setValues] = useState('')
values is a too generic name, please use something more representative of what is going to be stored here

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +      }}
please add this style to the styles folder

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +  const [values, setValues] = useState('')
maybe [category,setCategory]

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +        validate={(values) => {
please create a method to do this validation

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +        onSubmit={(values, { resetForm }) => {
please, create a onSubmit function

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +                style={{
all the styles on the style folder

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +                      fontStyle: 'italic',
all the styles on the style folder

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +              <ErrorMessage
this is being repeted, please refactor the code to create a function that show the errorMessage
```
const showErrorMessage = (name, message) => (component here)
```

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +                  fontWeight: 'bold',
styles on style folder. Also notice that you are repeting styles like fontWeight, maybe you can reuse them

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +                  onChange={(e) => {
please, create an onChange function

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesForm.js
> +                name='image'
this can be reused if you create a function

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesFormCreate.js
> +const CategoriesFormCreate = () => {
CategoriesCreationForm maybe its a better name, but its ok. (same on edit)

2021-10-28 22:31 UTC, saralavanchy commented on src/Components/Categories/CategoriesFunctions.js
> +export const getCategorie = (id) => async () => {
The view should read call the service, all the functionallity here is businnes rules that must be resolved on the service. This file is not necessary.

2021-10-28 22:32 UTC, saralavanchy commented
Please write a more descriptive title of what is being done in this PR. Also in the description maybe some title like
##Summary
##Screenshots
can help to understand the description.
Finally, if you can, please add a link to the user story.

2021-10-31 22:02 UTC, TelmaKn commented on src/Components/Categories/CategoriesFunctions.js
> +export const getCategorie = (id) => async () => {
oh! sorry! done.

2021-10-31 22:04 UTC, TelmaKn commented on src/Components/Categories/CategoriesForm.js
> +  const [values, setValues] = useState('')
It's true, done!

2021-10-31 22:08 UTC, TelmaKn commented on src/Components/Categories/CategoriesForm.js
> +                style={{
I deleted them until I have the style decided by the group.

2021-10-31 22:11 UTC, TelmaKn commented on src/Components/Categories/CategoriesForm.js
> +                      fontStyle: 'italic',
I deleted them until I have the style decided by the group.

2021-10-31 22:12 UTC, TelmaKn commented on src/Components/Categories/CategoriesForm.js
> +                  fontWeight: 'bold',
Ok. it's true! I deleted them!

2021-10-31 22:14 UTC, TelmaKn commented on src/Components/Categories/CategoriesForm.js
> +      }}
eliminated!

2021-10-31 22:15 UTC, TelmaKn commented on src/Components/Categories/CategoriesForm.js
> +        onSubmit={(values, { resetForm }) => {
well, it's done! :)

2021-10-31 22:37 UTC, TelmaKn commented on src/Components/Categories/CategoriesFormCreate.js
> +const CategoriesFormCreate = () => {
done! :)

2021-10-31 22:38 UTC, TelmaKn commented on src/Components/Categories/CategoriesForm.js
> +      const categorieData = functions.getCategorie(id)
Well I spent them there

2021-11-01 02:14 UTC, closed without merging

2021-11-01 02:48 UTC, TelmaKn commented on src/Components/Categories/CategoriesForm.js
> +              <ErrorMessage
Done

2021-11-01 02:49 UTC, TelmaKn commented on src/Components/Categories/CategoriesForm.js
> +                name='image'
Done!

2021-11-01 02:52 UTC, TelmaKn commented
I worked a lot trying to extract the onChange function from the CKEditor input but I'm having troubles with setFieldValues. The other requested chnages are done. I'll keep working on the onChange.