Feat/alert testimonial/render alert error request testimonials
alkemyTech/OT91-server pull request #85
Opened 2021-11-11 01:35 UTC by andreajhl

-reset an alert if the request throws an error
-the alert disappears after 3 seconds
-the alert says that action failed

![1](https://user-images.githubusercontent.com/75461111/141221151-8a8e2f95-7a6b-4ba8-a35c-2a0aceeb121f.png)

2021-11-11 21:00 UTC, saralavanchy requested changes

2021-11-11 21:00 UTC, saralavanchy commented on src/Components/common/text/textTestimonial.js
> +export const ERROR_CREATE = 'No se ha podido crear el Testimonio';
I like this idea of file, its an excelent and reusable concepts. I recommend to insted of adding an specific file for testimonial create a constants file under common and add this code there

 src/Components/common/constants.ts
```
export const ERROR_CREATE_TESTIMONIAL = 'No se ha podido crear el Testimonio';
export const ERROR_EDIT_TESTIMONIAL= 'No se ha podido modificar el Testimonio';
```

2021-11-11 21:00 UTC, saralavanchy commented on src/Services/testimonialService.js
> +        verifyStatus('buscar')
you should send the error.message

2021-11-11 21:00 UTC, saralavanchy commented on src/Services/testimonialService.js
> +function verifyStatus (status,message='An error occurred') {
instead of verifyStatus it should be mapError or showError, because it's not verifying any status, its showing an error

2021-11-11 21:14 UTC, andreajhl commented on src/Components/common/text/textTestimonial.js
> +export const ERROR_CREATE = 'No se ha podido crear el Testimonio';
listo, ya lo paso todo al que esta con los textos de activities tambien

2021-11-11 21:15 UTC, andreajhl commented on src/Services/testimonialService.js
> +        verifyStatus('buscar')
I don't understand what you mean by error msg? this function invokes another that renders the alert with the error message

2021-11-12 21:51 UTC, saralavanchy requested changes

2021-11-12 21:51 UTC, saralavanchy commented on src/Services/testimonialService.js
> +        verifyStatus('buscar')
cuando algo sale mal en el axios retorna un error explicando que paso. error tiene un error.message attribute que posee la informacion del error, en vez de hardcodear el mensjae con algo demaciado generico que no da info deberias pasar el mensaje de error de axios.

2021-11-12 21:51 UTC, saralavanchy commented on src/Components/common/text/textTestimonial.js
> +export const ERROR_CREATE = 'No se ha podido crear el Testimonio';
siguen estando en src/Components/common/text/textTestimonial.js

2021-11-16 20:19 UTC, saralavanchy approved these changes

2021-11-16 20:20 UTC, merged